services:
  app:
    build: .
    container_name: metrics_app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - metrics_network

  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: metrics_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - metrics_network

  alertmanager:
    image: prom/alertmanager:v0.33.0
    container_name: metrics_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - metrics_network

  receiver:
    build: .
    command: ["python", "receiver.py"]
    container_name: metrics_receiver
    ports:
      - "5001:5001"
    networks:
      - metrics_network

networks:
  metrics_network:
    driver: bridge
